### ISSUE TITLE
Service/port change

### ISSUE THREAD

**Issue by martijndeb** [theimpossibleastronaut/aawordsearch#13]
Shouldn't the default protocol be changed to https? I mean it's an encrypted connection, and they all seem to support it.

**Comment by andy5995** [comment]
Yes, I think you're right. I've tried that before but it hangs.

Did a bit of reading, and I think changes to get it working would be something like:

https://wiki.openssl.org/index.php/SSL/TLS_Client

**Comment by andy5995** [comment]
Or maybe libcurl could be used to simplify things https://curl.se/libcurl/c/example.html
